version: "3"

services:

  # index, search & aggregation
  elasticsearch:
    image: elasticsearch:6.5.0
    container_name: elastic
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - $PWD/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - elk

    # UI
  kibana:
    image: kibana:6.5.0
    container_name: kibana
    ports:
      - 5601:5601
    volumes:
      - $PWD/kibana/config/kibana.yml:/etc/kibana/kibana.yml
    networks:
      - elk
    depends_on:
      - elasticsearch

    # indexer
  logstash:
    image: logstash:6.5.0
    container_name: logstash
    command: logstash -f /config/
    ports:
      - 9500:9500
    volumes:
      - $PWD/logstash/config:/config
    networks:
      - elk
    depends_on:
      - elasticsearch


networks:
  elk:
    driver: bridge




#version: '3.5'

#services:
#
#  elasticsearch:
#    build:
#      context: elasticsearch/
#    volumes:
#    - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
#    ports:
#    - "9200:9200"
#    - "9300:9300"
#    networks:
#    - elk
#
#    logstash:
#      build:
#        context: logstash/
#      volumes:
#      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
#      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
#      ports:
#      - "5000:5000"
#      networks:
#      - elk
#      depends_on:
#      - elasticsearch
#
#  kibana:
#    build:
#      context: kibana/
#    volumes:
#    - ./kibana/config/:/usr/share/kibana/config:ro
#    ports:
#    - "5601:5601"
#    networks:
#    - elk
#    depends_on:
#    - elasticsearch
#
#networks:
#  elk:
#    driver: bridge