version: "3"

services:
  # index, search & aggregation
  elasticsearch:
    image: elasticsearch:6.5.0
    container_name: elastic
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - logging

    # UI
  kibana:
    image: kibana:6.5.0
    container_name: kibana
    ports:
      - 5601:5601
    networks:
      - logging
    depends_on:
      - elasticsearch

networks:
  logging:
    driver: bridge